theme: mini-hugo
themesDir: ../../

title: "An example site"

params:
  author: Jorge Sanz

disableKinds:
  - taxonomy
  - term
  - RSS
  - sitemap
  - 404

relativeURLs: true
defaultContentLanguage: en
